### ISSUE TITLE
[Bug] When entering the date, if the number is not two-digits it crashes the app

### ISSUE THREAD

**Issue by fadihajjej** [lainsce/countdown#1]
hey it seems like the app crashes when entering a single digit day or month as you can see in the video provided

https://user-images.githubusercontent.com/53702108/164367601-d13e1314-25b3-4a41-9e4d-7f7f773421a8.mp4

**Comment by lainsce** [comment]
Yeah, it should be always two numbers, so "06" in your case.

It's MM not M for the month. :)

**Comment by lainsce** [comment]
fixed
