### ISSUE TITLE
Gnome extension support

### ISSUE THREAD

**Issue by 0versun** [lainsce/countdown#20]
Feature request:
- Nice to have Gnome extension support or version that can show on top bar major event countdown 

example:

![image](https://github.com/lainsce/countdown/assets/17294426/25bc31b7-df7d-400a-8ed2-a83b013034f2)

**Comment by lainsce** [comment]
A GNOME Extension is a different thing that apps can't provide on their own. Sorry.

**Comment by 0versun** [comment]
Not really different, your app can support tray notification or tray setup and display additional info in tray

**Comment by lainsce** [comment]
Not how it works hehe
